export interface Surah {
  number: number;
  name: string;
  arabicName: string;
  ayahs: number;
  revelationType: 'Meccan' | 'Medinan';
}

export const surahList: Surah[] = [
  { number: 1, name: 'Al-Fatiha', arabicName: 'الفاتحة', ayahs: 7, revelationType: 'Meccan' },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', ayahs: 286, revelationType: 'Medinan' },
  { number: 3, name: 'Ali \'Imran', arabicName: 'آل عمران', ayahs: 200, revelationType: 'Medinan' },
  { number: 4, name: 'An-Nisa', arabicName: 'النساء', ayahs: 176, revelationType: 'Medinan' },
  { number: 5, name: 'Al-Ma\'idah', arabicName: 'المائدة', ayahs: 120, revelationType: 'Medinan' },
  { number: 6, name: 'Al-An\'am', arabicName: 'الأنعام', ayahs: 165, revelationType: 'Meccan' },
  { number: 7, name: 'Al-A\'raf', arabicName: 'الأعراف', ayahs: 206, revelationType: 'Meccan' },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', ayahs: 75, revelationType: 'Medinan' },
  { number: 9, name: 'At-Tawbah', arabicName: 'التوبة', ayahs: 129, revelationType: 'Medinan' },
  { number: 10, name: 'Yunus', arabicName: 'يونس', ayahs: 109, revelationType: 'Meccan' },
  { number: 11, name: 'Hud', arabicName: 'هود', ayahs: 123, revelationType: 'Meccan' },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', ayahs: 111, revelationType: 'Meccan' },
  { number: 13, name: 'Ar-Ra\'d', arabicName: 'الرعد', ayahs: 43, revelationType: 'Medinan' },
  { number: 14, name: 'Ibrahim', arabicName: 'ابراهيم', ayahs: 52, revelationType: 'Meccan' },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', ayahs: 99, revelationType: 'Meccan' },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', ayahs: 128, revelationType: 'Meccan' },
  { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', ayahs: 111, revelationType: 'Meccan' },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', ayahs: 110, revelationType: 'Meccan' },
  { number: 19, name: 'Maryam', arabicName: 'مريم', ayahs: 98, revelationType: 'Meccan' },
  { number: 20, name: 'Taha', arabicName: 'طه', ayahs: 135, revelationType: 'Meccan' },
  { number: 21, name: 'Al-Anbya', arabicName: 'الأنبياء', ayahs: 112, revelationType: 'Meccan' },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', ayahs: 78, revelationType: 'Medinan' },
  { number: 23, name: 'Al-Mu\'minun', arabicName: 'المؤمنون', ayahs: 118, revelationType: 'Meccan' },
  { number: 24, name: 'An-Nur', arabicName: 'النور', ayahs: 64, revelationType: 'Medinan' },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', ayahs: 77, revelationType: 'Meccan' },
  { number: 26, name: 'Ash-Shu\'ara', arabicName: 'الشعراء', ayahs: 227, revelationType: 'Meccan' },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', ayahs: 93, revelationType: 'Meccan' },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', ayahs: 88, revelationType: 'Meccan' },
  { number: 29, name: 'Al-\'Ankabut', arabicName: 'العنكبوت', ayahs: 69, revelationType: 'Meccan' },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', ayahs: 60, revelationType: 'Meccan' },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', ayahs: 34, revelationType: 'Meccan' },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', ayahs: 30, revelationType: 'Meccan' },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', ayahs: 73, revelationType: 'Medinan' },
  { number: 34, name: 'Saba', arabicName: 'سبأ', ayahs: 54, revelationType: 'Meccan' },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', ayahs: 45, revelationType: 'Meccan' },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', ayahs: 83, revelationType: 'Meccan' },
  { number: 37, name: 'As-Saffat', arabicName: 'الصافات', ayahs: 182, revelationType: 'Meccan' },
  { number: 38, name: 'Sad', arabicName: 'ص', ayahs: 88, revelationType: 'Meccan' },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', ayahs: 75, revelationType: 'Meccan' },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', ayahs: 85, revelationType: 'Meccan' },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', ayahs: 54, revelationType: 'Meccan' },
  { number: 42, name: 'Ash-Shuraa', arabicName: 'الشورى', ayahs: 53, revelationType: 'Meccan' },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', ayahs: 89, revelationType: 'Meccan' },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', ayahs: 59, revelationType: 'Meccan' },
  { number: 45, name: 'Al-Jathiyah', arabicName: 'الجاثية', ayahs: 37, revelationType: 'Meccan' },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', ayahs: 35, revelationType: 'Meccan' },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', ayahs: 38, revelationType: 'Medinan' },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', ayahs: 29, revelationType: 'Medinan' },
  { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', ayahs: 18, revelationType: 'Medinan' },
  { number: 50, name: 'Qaf', arabicName: 'ق', ayahs: 45, revelationType: 'Meccan' },
  { number: 51, name: 'Adh-Dhariyat', arabicName: 'الذاريات', ayahs: 60, revelationType: 'Meccan' },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', ayahs: 49, revelationType: 'Meccan' },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', ayahs: 62, revelationType: 'Meccan' },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', ayahs: 55, revelationType: 'Meccan' },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', ayahs: 78, revelationType: 'Meccan' },
  { number: 56, name: 'Al-Waqi\'ah', arabicName: 'الواقعة', ayahs: 96, revelationType: 'Meccan' },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', ayahs: 29, revelationType: 'Medinan' },
  { number: 58, name: 'Al-Mujadila', arabicName: 'المجادلة', ayahs: 22, revelationType: 'Medinan' },
  { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', ayahs: 24, revelationType: 'Medinan' },
  { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', ayahs: 13, revelationType: 'Medinan' },
  { number: 61, name: 'As-Saff', arabicName: 'الصف', ayahs: 14, revelationType: 'Medinan' },
  { number: 62, name: 'Al-Jumu\'ah', arabicName: 'الجمعة', ayahs: 11, revelationType: 'Medinan' },
  { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', ayahs: 11, revelationType: 'Medinan' },
  { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', ayahs: 18, revelationType: 'Medinan' },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', ayahs: 12, revelationType: 'Medinan' },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', ayahs: 12, revelationType: 'Medinan' },
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', ayahs: 30, revelationType: 'Meccan' },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', ayahs: 52, revelationType: 'Meccan' },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', ayahs: 52, revelationType: 'Meccan' },
  { number: 70, name: 'Al-Ma\'arij', arabicName: 'المعارج', ayahs: 44, revelationType: 'Meccan' },
  { number: 71, name: 'Nuh', arabicName: 'نوح', ayahs: 28, revelationType: 'Meccan' },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', ayahs: 28, revelationType: 'Meccan' },
  { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', ayahs: 20, revelationType: 'Meccan' },
  { number: 74, name: 'Al-Muddaththir', arabicName: 'المدثر', ayahs: 56, revelationType: 'Meccan' },
  { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', ayahs: 40, revelationType: 'Meccan' },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', ayahs: 31, revelationType: 'Medinan' },
  { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', ayahs: 50, revelationType: 'Meccan' },
  { number: 78, name: 'An-Naba', arabicName: 'النبأ', ayahs: 40, revelationType: 'Meccan' },
  { number: 79, name: 'An-Nazi\'at', arabicName: 'النازعات', ayahs: 46, revelationType: 'Meccan' },
  { number: 80, name: 'Abasa', arabicName: 'عبس', ayahs: 42, revelationType: 'Meccan' },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', ayahs: 29, revelationType: 'Meccan' },
  { number: 82, name: 'Al-Infitar', arabicName: 'الإنفطار', ayahs: 19, revelationType: 'Meccan' },
  { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', ayahs: 36, revelationType: 'Meccan' },
  { number: 84, name: 'Al-Inshiqaq', arabicName: 'الإنشقاق', ayahs: 25, revelationType: 'Meccan' },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', ayahs: 22, revelationType: 'Meccan' },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', ayahs: 17, revelationType: 'Meccan' },
  { number: 87, name: 'Al-A\'la', arabicName: 'الأعلى', ayahs: 19, revelationType: 'Meccan' },
  { number: 88, name: 'Al-Ghashiyah', arabicName: 'الغاشية', ayahs: 26, revelationType: 'Meccan' },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', ayahs: 30, revelationType: 'Meccan' },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', ayahs: 20, revelationType: 'Meccan' },
  { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', ayahs: 15, revelationType: 'Meccan' },
  { number: 92, name: 'Al-Layl', arabicName: 'الليل', ayahs: 21, revelationType: 'Meccan' },
  { number: 93, name: 'Ad-Duhaa', arabicName: 'الضحى', ayahs: 11, revelationType: 'Meccan' },
  { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', ayahs: 8, revelationType: 'Meccan' },
  { number: 95, name: 'At-Tin', arabicName: 'التين', ayahs: 8, revelationType: 'Meccan' },
  { number: 96, name: 'Al-\'Alaq', arabicName: 'العلق', ayahs: 19, revelationType: 'Meccan' },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', ayahs: 5, revelationType: 'Meccan' },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', ayahs: 8, revelationType: 'Medinan' },
  { number: 99, name: 'Az-Zalzalah', arabicName: 'الزلزلة', ayahs: 8, revelationType: 'Medinan' },
  { number: 100, name: 'Al-\'Adiyat', arabicName: 'العاديات', ayahs: 11, revelationType: 'Meccan' },
  { number: 101, name: 'Al-Qari\'ah', arabicName: 'القارعة', ayahs: 11, revelationType: 'Meccan' },
  { number: 102, name: 'At-Takathur', arabicName: 'التكاثر', ayahs: 8, revelationType: 'Meccan' },
  { number: 103, name: 'Al-\'Asr', arabicName: 'العصر', ayahs: 3, revelationType: 'Meccan' },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', ayahs: 9, revelationType: 'Meccan' },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', ayahs: 5, revelationType: 'Meccan' },
  { number: 106, name: 'Quraysh', arabicName: 'قريش', ayahs: 4, revelationType: 'Meccan' },
  { number: 107, name: 'Al-Ma\'un', arabicName: 'الماعون', ayahs: 7, revelationType: 'Meccan' },
  { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', ayahs: 3, revelationType: 'Meccan' },
  { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', ayahs: 6, revelationType: 'Meccan' },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', ayahs: 3, revelationType: 'Medinan' },
  { number: 111, name: 'Al-Masad', arabicName: 'المسد', ayahs: 5, revelationType: 'Meccan' },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', ayahs: 4, revelationType: 'Meccan' },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', ayahs: 5, revelationType: 'Meccan' },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', ayahs: 6, revelationType: 'Meccan' },
];

export default surahList; 